name: PR Checks against develop branch
on:
  pull_request:
    branches: [develop]
    types: [opened, synchronize, closed]
jobs:
  build:
    runs-on: [self-hosted, Linux, X64, Ubuntu]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - run: |
          cd $GITHUB_WORKSPACE && pwd
          if [ ! -d .git ]; then git init; git config user.email "you@dummy.com"; git config user.name "dummy"; git add --all && git commit -q -m "Only fix mvn goals for github workflow"; fi
          if [ -f ~/.cskefu.rc ]; then source ~/.cskefu.rc; else echo "Not found ~/.cskefu.rc; find info with https://github.com/cskefu/cskefu/issues/688"; exit 1; fi
          java -version && mvn -version
          $GITHUB_WORKSPACE/plugins/bin/buildAll.sh
          $GITHUB_WORKSPACE/server/bin/package.sh
